# Relevant file/directory paths
PATHS:
  RAW_DATA: 'data/raw/'
  CONSUMPTION_DATA: 'data/preprocessed/consumption_data.csv'
  PREPROCESSED_OHE_DATA: 'data/preprocessed/preprocessed_OHE.csv'
  CAT_FEAT_MAP: 'data/serializations/cat_feat_map.yml'
  MODEL_WEIGHTS: 'results/models/'
  MODEL_TO_LOAD: 'results/models/model.h5'
  VISUALIZATIONS: 'img/visualizations/'
  LOGS: 'results\\logs\\'
  EXPERIMENTS: 'results/experiments/'
  TRAIN_SET: 'data/preprocessed/Train_Set.csv'
  TEST_SET: 'data/preprocessed/Test_Set.csv'
  SCALER_COL_TRANSFORMER: 'data/serializations/scaler_col_transformer.bin'
  ORDINAL_COL_TRANSFORMER: 'data/serializations/ordinal_col_transformer.bin'
  OHE_COL_TRANSFORMER: 'data/serializations/ohe_transformer_sv.bin'
  PREDICTIONS: './results/predictions/'

DATA:
  NUMERICAL_FEATS: []
  CATEGORICAL_FEATS: []