# Relevant file/directory paths
PATHS:
  RAW_DATA: 'data/raw/'
  CONSUMPTION_DATA: 'data/preprocessed/consumption_data.csv'
  PREPROCESSED_DATA: 'data/preprocessed/preprocessed_data.csv'
  INTERMEDIATE_DATA: 'data/preprocessed/intermediate_data.csv'
  CLIENT_DATA: 'data/preprocessed/client_data.csv'
  CAT_FEAT_MAP: 'data/serializations/cat_feat_map.yml'
  MODELS: 'results/models/'
  MODEL_TO_LOAD: 'results/models/model.h5'
  DATA_VISUALIZATIONS: 'img/data_visualizations/'
  FORECAST_VISUALIZATIONS: 'img/forecast_visualizations/'
  EXPERIMENT_VISUALIZATIONS: 'img/experiment_visualizations/'
  LOGS: 'results\\logs\\'
  EXPERIMENTS: 'results/experiments/'
  TRAIN_SET: 'data/preprocessed/Train_Set.csv'
  TEST_SET: 'data/preprocessed/Test_Set.csv'
  SCALER_COL_TRANSFORMER: 'data/serializations/scaler_col_transformer.bin'
  ORDINAL_COL_TRANSFORMER: 'data/serializations/ordinal_col_transformer.bin'
  OHE_COL_TRANSFORMER: 'data/serializations/ohe_transformer_sv.bin'
  PREDICTIONS: './results/predictions/'
  K-PROTOTYPES_CENTROIDS: 'results/experiments/cluster_centroids_'
  K-PROTOTYPES_CLUSTERS: 'results/experiments/client_clusters_'
  IMAGES: './img/visualizations/'

# Constants describing data
DATA:
  NUMERICAL_FEATS: ['PARCEL_AREA', 'SSF', 'REDUC_FAC', 'NOM', 'BILLING_AREA', 'W_HEC_AF', 'PREMISE_UNITS']
  CATEGORICAL_FEATS: ['RATE_CLASS', 'METER_SIZE', 'INST_TYPE', 'EST_READ']
  BOOLEAN_FEATS: ['SERVICE_STATUS', 'RES_LDM', 'RES_MDM', 'RES_HR', 'S90MT', 'FIRE_PROT_CHARGE_EXEMPT',
                  'CUST_ASST_PROG_EXEMPT', 'STORM_CHARGE_EX', 'SAN_CHARGE_EX', 'WATER_CHARGE_EX']
  EVAL_DATE: '2020-09-17'
  TEST_FRAC: 0.2

# Training experiments
TRAIN:
  MODEL: 'prophet'
  EXPERIMENT: 'train_single'
  N_FOLDS: 6
  HPARAM_SEARCH:
    MAX_EVALS: 500
    HPARAM_OBJECTIVE: 'MAPE'
    LAST_FOLDS: 4

# Hyperparameters specific to individual models
HPARAMS:
  PROPHET:
    COUNTRY: 'CA'
    CHANGEPOINT_PRIOR_SCALE: 0.052
    SEASONALITY_PRIOR_SCALE: 9.94
    HOLIDAYS_PRIOR_SCALE: 0.104
    SEASONALITY_MODE: 'multiplicative'
    CHANGEPOINT_RANGE: 0.95
    HOLIDAYS:
      Family Day: ['2008-02-18', '2009-02-16', '2010-02-15', '2011-02-21', '2012-02-20', '2013-02-18', '2014-02-17',
                    '2015-02-16', '2016-02-15', '2017-02-20', '2018-02-19', '2019-02-18', '2020-02-17', '2021-02-15',
                    '2022-02-21', '2023-02-20', '2024-02-19']
      Civic Holiday: ['2008-08-04', '2009-08-03', '2010-08-02', '2011-08-01', '2012-08-06', '2013-08-05',
                        '2014-08-04', '2015-08-03', '2016-08-01', '2017-08-07', '2018-08-06', '2019-08-05',
                        '2020-08-03', '2021-08-02', '2022-08-01', '2023-08-07', '2024-08-05']
  ARIMA:
    AUTO_PARAMS: false
    P: 7
    D: 1
    Q: 30
  SARIMA:
    AUTO_PARAMS: false
    TREND_P: 7
    TREND_D: 1
    TREND_Q: 0
    SEASONAL_P: 1
    SEASONAL_D: 1
    SEASONAL_Q: 0
    M: 365
  LSTM:
    UNIVARIATE: true
    T_X: 248
    BATCH_SIZE: 32
    EPOCHS: 500
    PATIENCE: 7
    VAL_FRAC: 0.1
    LR: 0.000718
    LOSS: 'huber_loss'
    UNITS: 128
    DROPOUT: 0.0017
    FC0_UNITS: 32
    FC1_UNITS: 64
  GRU:
    UNIVARIATE: true
    T_X: 365
    BATCH_SIZE: 32
    EPOCHS: 500
    PATIENCE: 10
    VAL_FRAC: 0.1
    LR: 0.001
    LOSS: 'mse'
    UNITS: 16
    DROPOUT: 0.25
    FC0_UNITS: 32
    FC1_UNITS: 16
  1DCNN:
    UNIVARIATE: true
    T_X: 53
    BATCH_SIZE: 64
    EPOCHS: 300
    PATIENCE: 11
    VAL_FRAC: 0.1
    LR: 0.00001
    LOSS: 'mae'
    FILTERS: 8
    KERNEL_SIZE: 3
    STRIDE: 2
    N_CONV_LAYERS: 1
    FC0_UNITS: 64
    FC1_UNITS: 8
    DROPOUT: 0.0
  LINEAR_REGRESSION:
    UNIVARIATE: true
    T_X: 365
  RANDOM_FOREST:
    UNIVARIATE: true
    T_X: 365
    N_ESTIMATORS: 100
    LOSS: 'mse'

HPARAM_SEARCH:
  PROPHET:
    CHANGEPOINT_PRIOR_SCALE:
      TYPE: 'float_log'
      RANGE: [0.001, 0.5]
    SEASONALITY_PRIOR_SCALE:
      TYPE: 'float_log'
      RANGE: [0.01, 10]
    HOLIDAYS_PRIOR_SCALE:
      TYPE: 'float_log'
      RANGE: [0.01, 10]
    SEASONALITY_MODE:
      TYPE: 'set'
      RANGE: ['additive', 'multiplicative']
  LSTM:
    T_X:
      TYPE: 'int_uniform'
      RANGE: [30, 365]
    BATCH_SIZE:
      TYPE: 'set'
      RANGE: [16, 32]
    PATIENCE:
      TYPE: 'int_uniform'
      RANGE: [5, 15]
    LR:
      TYPE: 'float_log'
      RANGE: [0.00001, 0.001]
    LOSS:
      TYPE: 'set'
      RANGE: ['mse', 'mae', 'huber_loss']
    UNITS:
      TYPE: 'set'
      RANGE: [8, 16, 32, 64, 128]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]
    FC0_UNITS:
      TYPE: 'set'
      RANGE: [32, 64, 128]
    FC1_UNITS:
      TYPE: 'set'
      RANGE: [16, 32, 64]
    #FC2_UNITS:
    #  TYPE: 'set'
    #  RANGE: [8, 16, 32, 64]
  1DCNN:
    T_X:
      TYPE: 'int_uniform'
      RANGE: [30, 60]
    BATCH_SIZE:
      TYPE: 'set'
      RANGE: [16, 32, 64]
    PATIENCE:
      TYPE: 'int_uniform'
      RANGE: [5, 15]
    LR:
      TYPE: 'float_log'
      RANGE: [0.00001, 0.001]
    LOSS:
      TYPE: 'set'
      RANGE: ['mse', 'mae', 'huber_loss']
    FILTERS:
      TYPE: 'set'
      RANGE: [8, 16, 32, 64, 128]
    KERNEL_SIZE:
      TYPE: 'set'
      RANGE: [3, 5]
    STRIDE:
      TYPE: 'int_uniform'
      RANGE: [1, 2]
    N_CONV_LAYERS:
      TYPE: 'int_uniform'
      RANGE: [1, 5]
    DROPOUT:
      TYPE: 'float_uniform'
      RANGE: [0.0, 0.5]
    FC0_UNITS:
      TYPE: 'set'
      RANGE: [32, 64, 128, 256]
    FC1_UNITS:
      TYPE: 'set'
      RANGE: [16, 32, 64, 128]
    FC2_UNITS:
      TYPE: 'set'
      RANGE: [8, 16, 32, 64]

# Data clustering
K-PROTOTYPES:
  K: 4
  N_RUNS: 15
  N_JOBS: 3
  K_MIN: 3
  K_MAX: 12
  FEATS_TO_EXCLUDE: ['RATE_CLASS', 'NOM', 'REDUC_FAC', 'SSF', 'W_HEC_AF', 'RES_LDM', 'RES_MDM', 'RES_HR']
  EXPERIMENT: 'cluster_clients'               # One of {'cluster_clients', 'silhouette_analysis'}