# Relevant file/directory paths
PATHS:
  RAW_DATA: 'data/raw/'
  CONSUMPTION_DATA: 'data/preprocessed/consumption_data.csv'
  PREPROCESSED_DATA: 'data/preprocessed/preprocessed_data.csv'
  INTERMEDIATE_DATA: 'data/preprocessed/intermediate_data.csv'
  CLIENT_DATA: 'data/preprocessed/client_data.csv'
  CAT_FEAT_MAP: 'data/serializations/cat_feat_map.yml'
  MODELS: 'results/models/'
  MODEL_TO_LOAD: 'results/models/model.h5'
  DATA_VISUALIZATIONS: 'img/data_visualizations/'
  FORECAST_VISUALIZATIONS: 'img/forecast_visualizations/'
  LOGS: 'results\\logs\\'
  EXPERIMENTS: 'results/experiments/'
  TRAIN_SET: 'data/preprocessed/Train_Set.csv'
  TEST_SET: 'data/preprocessed/Test_Set.csv'
  SCALER_COL_TRANSFORMER: 'data/serializations/scaler_col_transformer.bin'
  ORDINAL_COL_TRANSFORMER: 'data/serializations/ordinal_col_transformer.bin'
  OHE_COL_TRANSFORMER: 'data/serializations/ohe_transformer_sv.bin'
  PREDICTIONS: './results/predictions/'
  K-PROTOTYPES_CENTROIDS: 'results/experiments/cluster_centroids_'
  K-PROTOTYPES_CLUSTERS: 'results/experiments/client_clusters_'
  IMAGES: './img/visualizations/'

# Constants describing data
DATA:
  NUMERICAL_FEATS: ['PARCEL_AREA', 'SSF', 'REDUC_FAC', 'NOM', 'BILLING_AREA', 'W_HEC_AF', 'PREMISE_UNITS']
  CATEGORICAL_FEATS: ['RATE_CLASS', 'METER_SIZE', 'INST_TYPE', 'EST_READ']
  BOOLEAN_FEATS: ['SERVICE_STATUS', 'RES_LDM', 'RES_MDM', 'RES_HR', 'S90MT', 'FIRE_PROT_CHARGE_EXEMPT',
                  'CUST_ASST_PROG_EXEMPT', 'STORM_CHARGE_EX', 'SAN_CHARGE_EX', 'WATER_CHARGE_EX']
  EVAL_DATE: '2020-09-17'
  TEST_FRAC: 0.2

# Training experiments
TRAIN:
  MODEL: 'arima'
  EXPERIMENT: 'train_single'

# Hyperparameters specific to individual models
HPARAMS:
  PROPHET:
    COUNTRY: 'CA'
    CHANGEPOINT_PRIOR_SCALE: 0.05
    SEASONALITY_PRIOR_SCALE: 10
    HOLIDAYS_PRIOR_SCALE: 10
    SEASONALITY_MODE: 'additive'
    CHANGEPOINT_RANGE: 0.95
    HOLIDAYS:
      Family Day: ['2008-02-18', '2009-02-16', '2010-02-15', '2011-02-21', '2012-02-20', '2013-02-18', '2014-02-17',
                    '2015-02-16', '2016-02-15', '2017-02-20', '2018-02-19', '2019-02-18', '2020-02-17', '2021-02-15',
                    '2022-02-21', '2023-02-20', '2024-02-19']
      Civic Holiday: ['2008-08-04', '2009-08-03', '2010-08-02', '2011-08-01', '2012-08-06', '2013-08-05',
                        '2014-08-04', '2015-08-03', '2016-08-01', '2017-08-07', '2018-08-06', '2019-08-05',
                        '2020-08-03', '2021-08-02', '2022-08-01', '2023-08-07', '2024-08-05']
  ARIMA:
    AUTO_PARAMS: false
    P: 7
    D: 1
    Q: 30
  SARIMA:
    AUTO_PARAMS: false
    TREND_P: 7
    TREND_D: 1
    TREND_Q: 0
    SEASONAL_P: 1
    SEASONAL_D: 1
    SEASONAL_Q: 0
    M: 365
  LSTM:
    UNIVARIATE: true
    T_X: 365
    BATCH_SIZE: 32
    EPOCHS: 300
    PATIENCE: 10
    VAL_SET_SIZE: 90
    LR: 0.001
    LOSS: 'mse'
    UNITS: 32
    DROPOUT: 0.25
    FC_UNITS: [128]
  GRU:
    UNIVARIATE: true
    T_X: 365
    BATCH_SIZE: 32
    EPOCHS: 300
    PATIENCE: 10
    VAL_SET_SIZE: 90
    LR: 0.001
    LOSS: 'mse'
    UNITS: 16
    DROPOUT: 0.25
    FC_UNITS: [128]
  1DCNN:
    UNIVARIATE: true
    T_X: 365
    BATCH_SIZE: 32
    EPOCHS: 300
    PATIENCE: 10
    VAL_SET_SIZE: 90
    LR: 0.001
    LOSS: 'mse'
    FILTERS: 16
    KERNEL_SIZE: 3
    FC_UNITS: [16, 8]
    DROPOUT: 0.25
  LINEAR_REGRESSION:
    UNIVARIATE: true
    T_X: 365
  RANDOM_FOREST:
    UNIVARIATE: true
    T_X: 365
    N_ESTIMATORS: 100
    LOSS: 'mse'


# Data clustering
K-PROTOTYPES:
  K: 4
  N_RUNS: 15
  N_JOBS: 3
  K_MIN: 3
  K_MAX: 12
  FEATS_TO_EXCLUDE: ['RATE_CLASS', 'NOM', 'REDUC_FAC', 'SSF', 'W_HEC_AF', 'RES_LDM', 'RES_MDM', 'RES_HR']
  EXPERIMENT: 'cluster_clients'               # One of {'cluster_clients', 'silhouette_analysis'}